gpt-5-instant:
  model_name: gpt-5-instant
  base_url: ${OPENAI_BASE_URL}
  api_key: ${OPENAI_API_KEY}
  default_temp: 0.3
  meta:
    is_thinking: false
    context_window: 200000
    cost_per_1k_input_tokens: 5.0
    cost_per_1k_output_tokens: 15.0
    rpm_limit: 5000

gpt-5-nano:
  model_name: gpt-5-nano
  base_url: ${OPENAI_BASE_URL}
  api_key: ${OPENAI_API_KEY}
  default_temp: 1.0
  meta:
    is_thinking: true
    reasoning_effort: medium
    context_window: 200000
    cost_per_1k_input_tokens: 3.0
    cost_per_1k_output_tokens: 10.0
    rpm_limit: 4000
    include:
      - reasoning
      - input
      - output

gpt-4.1-mini:
  model_name: gpt-4.1-mini
  base_url: ${OPENAI_BASE_URL}
  api_key: ${OPENAI_API_KEY}
  default_temp: 0.4
  meta:
    is_thinking: false
    context_window: 128000
    cost_per_1k_input_tokens: 3.0
    cost_per_1k_output_tokens: 12.0
    rpm_limit: 5000

o3-mini:
  model_name: o3-mini
  base_url: ${OPENAI_BASE_URL}
  api_key: ${OPENAI_API_KEY}
  default_temp: 1.0
  meta:
    is_thinking: true
    reasoning_effort: high
    reasoning_summary: short
    context_window: 128000
    cost_per_1k_input_tokens: 6.0
    cost_per_1k_output_tokens: 18.0
    rpm_limit: 3000
